/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Inquiry = IDL.Record({
  'destination' : IDL.Text,
  'name' : IDL.Text,
  'travelDates' : IDL.Text,
  'travelers' : IDL.Nat,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const Region = IDL.Variant({
  'central' : IDL.Null,
  'east' : IDL.Null,
  'west' : IDL.Null,
  'south' : IDL.Null,
  'north' : IDL.Null,
});
export const TourPackage = IDL.Record({
  'id' : IDL.Nat,
  'region' : Region,
  'destination' : IDL.Text,
  'duration' : IDL.Text,
  'name' : IDL.Text,
  'highlights' : IDL.Vec(IDL.Text),
  'category' : IDL.Text,
  'price' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getAllTourPackages' : IDL.Func([], [IDL.Vec(TourPackage)], ['query']),
  'getPackagesByRegion' : IDL.Func([Region], [IDL.Vec(TourPackage)], ['query']),
  'getTourPackageById' : IDL.Func([IDL.Nat], [TourPackage], ['query']),
  'seedTourPackages' : IDL.Func([], [], []),
  'submitInquiry' : IDL.Func([Inquiry], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Inquiry = IDL.Record({
    'destination' : IDL.Text,
    'name' : IDL.Text,
    'travelDates' : IDL.Text,
    'travelers' : IDL.Nat,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Region = IDL.Variant({
    'central' : IDL.Null,
    'east' : IDL.Null,
    'west' : IDL.Null,
    'south' : IDL.Null,
    'north' : IDL.Null,
  });
  const TourPackage = IDL.Record({
    'id' : IDL.Nat,
    'region' : Region,
    'destination' : IDL.Text,
    'duration' : IDL.Text,
    'name' : IDL.Text,
    'highlights' : IDL.Vec(IDL.Text),
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  
  return IDL.Service({
    'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getAllTourPackages' : IDL.Func([], [IDL.Vec(TourPackage)], ['query']),
    'getPackagesByRegion' : IDL.Func(
        [Region],
        [IDL.Vec(TourPackage)],
        ['query'],
      ),
    'getTourPackageById' : IDL.Func([IDL.Nat], [TourPackage], ['query']),
    'seedTourPackages' : IDL.Func([], [], []),
    'submitInquiry' : IDL.Func([Inquiry], [], []),
  });
};

export const init = ({ IDL }) => { return []; };