/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TourPackage {
    id: bigint;
    region: Region;
    destination: string;
    duration: string;
    name: string;
    highlights: Array<string>;
    category: string;
    price: bigint;
}
export interface Inquiry {
    destination: string;
    name: string;
    travelDates: string;
    travelers: bigint;
    email: string;
    message: string;
    phone: string;
}
export enum Region {
    central = "central",
    east = "east",
    west = "west",
    south = "south",
    north = "north"
}
export interface backendInterface {
    getAllInquiries(): Promise<Array<Inquiry>>;
    getAllTourPackages(): Promise<Array<TourPackage>>;
    getPackagesByRegion(region: Region): Promise<Array<TourPackage>>;
    getTourPackageById(id: bigint): Promise<TourPackage>;
    seedTourPackages(): Promise<void>;
    submitInquiry(inquiry: Inquiry): Promise<void>;
}
import type { Region as _Region, TourPackage as _TourPackage } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAllInquiries(): Promise<Array<Inquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInquiries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInquiries();
            return result;
        }
    }
    async getAllTourPackages(): Promise<Array<TourPackage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTourPackages();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTourPackages();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPackagesByRegion(arg0: Region): Promise<Array<TourPackage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPackagesByRegion(to_candid_Region_n6(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPackagesByRegion(to_candid_Region_n6(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTourPackageById(arg0: bigint): Promise<TourPackage> {
        if (this.processError) {
            try {
                const result = await this.actor.getTourPackageById(arg0);
                return from_candid_TourPackage_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTourPackageById(arg0);
            return from_candid_TourPackage_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async seedTourPackages(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedTourPackages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedTourPackages();
            return result;
        }
    }
    async submitInquiry(arg0: Inquiry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitInquiry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitInquiry(arg0);
            return result;
        }
    }
}
function from_candid_Region_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Region): Region {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_TourPackage_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TourPackage): TourPackage {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    region: _Region;
    destination: string;
    duration: string;
    name: string;
    highlights: Array<string>;
    category: string;
    price: bigint;
}): {
    id: bigint;
    region: Region;
    destination: string;
    duration: string;
    name: string;
    highlights: Array<string>;
    category: string;
    price: bigint;
} {
    return {
        id: value.id,
        region: from_candid_Region_n4(_uploadFile, _downloadFile, value.region),
        destination: value.destination,
        duration: value.duration,
        name: value.name,
        highlights: value.highlights,
        category: value.category,
        price: value.price
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    central: null;
} | {
    east: null;
} | {
    west: null;
} | {
    south: null;
} | {
    north: null;
}): Region {
    return "central" in value ? Region.central : "east" in value ? Region.east : "west" in value ? Region.west : "south" in value ? Region.south : "north" in value ? Region.north : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TourPackage>): Array<TourPackage> {
    return value.map((x)=>from_candid_TourPackage_n2(_uploadFile, _downloadFile, x));
}
function to_candid_Region_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Region): _Region {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Region): {
    central: null;
} | {
    east: null;
} | {
    west: null;
} | {
    south: null;
} | {
    north: null;
} {
    return value == Region.central ? {
        central: null
    } : value == Region.east ? {
        east: null
    } : value == Region.west ? {
        west: null
    } : value == Region.south ? {
        south: null
    } : value == Region.north ? {
        north: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
